name: Update pastpapers
on:
  workflow_dispatch:
    inputs:
      limit:
        description: "maximum attachment download count"
        required: false
        default: '0'
      

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/workflows/requirements.txt
    - name: Run the script 
      run: |
        python3 ./.github/workflows/scrapper.py . --thread 50 --delay 0 --retries 10 --suffix .pdf .zip --limit ${{ inputs.limit }}
    - name: Push changes
      run: |
        bash ./.github/workflows/push_in_batches.sh
